name: Bug report
description: Something isn't working as it should be
labels: ["bug"]

body:
- type: textarea
  attributes:
    label: Description
    description: |
      Describe the bug, give us as much details as you can.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
       How to reproduce the bug.
    placeholder: |
       1. Go to...
       2. Click....
       3. Then...
  validations:
    required: true
     
- type: input
  attributes:
    label: Game version
    description: |
      Specify the version of the game.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Platform
    description: |
      If the issue is specific to a platform, providing your platform/OS will be very helpful.
    options: ["Windows", "Linux", "Nintendo 3DS"]
  validations:
    required: true

- type: checkboxes
  attributes:
    description: Before submitting a bug, please search for similar [issues](https://github.com/Wolfyxon/TurretSiege/issues)
    options:
      - label: I have done the search for similar issues
        required: true