name: Question
description: Question or something else
title: "[QUESTION]: "
labels: ["question"]

body:
- type: textarea
  attributes:
    label: Description
    description: |
      Describe your question.
  validations:
    required: true
